### ISSUE TITLE
Help! I can't build ext-vanillagenerator on Win 10

### ISSUE THREAD

**Issue by Neerdex** [NetherGamesMC/noiselib#6]
I'm using the https://github.com/NetherGamesMC/php-build-scripts

compile.log:
---
[PocketMine] PHP Windows compiler 
[PocketMine] Setting up environment... 
[PocketMine] Building release binaries with debug symbols 
[PocketMine] Compiling with configuration for PocketMine-MP  
[PocketMine] Using path C:\pocketmine-php-8.2.7-release for build sources 
[PocketMine] Found Visual Studio 2019 
The system cannot find the specified path.
[PocketMine] [ERROR] Error initializing Visual Studio environment - check compile.log for details 
---
Whats wrong here?

How to build ext-vanillagenerator in Windows 10?

**Comment by larryTheCoder** [comment]
Please use the provided builds on the releases page. You can download the PM4 or PM5 builds [here](https://github.com/NetherGamesMC/php-build-scripts/releases)
