### ISSUE TITLE
Generation error

### ISSUE THREAD

**Issue by 6kek6** [NetherGamesMC/noiselib#7]
At negative coordinates (-X and -Z) the generation breaks down, there are only fields and a few mountains. Lack of trees and vegetation in general + biomes are chaotic.

**Comment by larryTheCoder** [comment]
Is it possible for you to provide more information such as your terrain seed value and the OS you are using? This issue could be related to the use of custom integer width size.

**Comment by 6kek6** [comment]
I didn’t do anything additional, I created a new world: on positive coordinates everything is fine, but on negative coordinates there are problems. There are no modifications with the world, I checked it several times, it’s always like this. 

Os: Ubuntu 20.04
Php-build: by NetherGames last version

**Comment by larryTheCoder** [comment]
I will start investigating this bug this sunday, I am a bit unavailable to debug this issue this week so I am sorry if we are a bit slow.
