### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 6kek6** [NetherGamesMC/noiselib#9]
terminate called after throwing an instance of 'std::invalid_argument'
 what():  10265:256 is already mapped
Aborted

**Comment by larryTheCoder** [comment]
Fixed in the latest version, update your VanillaGenerator plugin to [v1.1.1](https://github.com/NetherGamesMC/VanillaGenerator/releases/tag/1.1.1) and download the binaries as explained in the release tag there.
